# Chat Completion - POST - the api-version value would be passed to openi, NOT to apim

@subscription-standard = 2a903f92bed249ad847d2882322a04de
@subscription-premium = afb487599b0546d0a1b01e7474982cff


@APIM-API-Endpoint = https://mmapim02.azure-api.net/balanced-azure-openai-service-api/openai
@APIM-API-Operation-Path = /deployments/gpt-4o-for-apim/chat/completions
@APIM-Subscription-Key = afb487599b0546d0a1b01e7474982cff


POST {{APIM-API-Endpoint}}{{APIM-API-Operation-Path}}
api-key: {{APIM-Subscription-Key}}

{
  "max_tokens": 500,
  "messages": [
    {
      "role": "user",
      "content": "Hi there!"
    }
  ]
}