# $token=$(az account get-access-token --query accessToken --output tsv)
@env                 = mauromiapim01
@subscription_id     = 
@apim-name           = mauromiapim01

@resource-group-name = mmcognitivegrp

@apim-api-version    = 2023-09-01-preview

@backend-openai-main-name = backend-openai-main-mmopenaisec
@backend-openai-main-url  = https://mmoaiswc-01.openai.azure.com/openai

@backend-openai-fallback-name = backend-openai-fallback-mmopenaiscus
@backend-openai-fallback-url  = https://mmoaiscus-01.openai.azure.com/openai

@backend-openai-pool-name = backend-openai-pool



# Backend - Fallback (no restrictions)
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-fallback-name}}?api-version={{apim-api-version}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "properties": {
    "title": "{{backend-openai-fallback-name}}",
    "description": "{{backend-openai-fallback-name}}",
    "url": "{{backend-openai-fallback-url}}",
    "protocol": "http",
    "tls": {
      "validateCertificateChain": true,
      "validateCertificateName": true
    }
  }
}


###

# Backend Retrieval using GET
@backendToRetrieve={{backend-openai-fallback-name}}
GET https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-fallback-name}}?api-version={{apim-api-version}}
Authorization: Bearer {{Token}}

###


# Backend - Main with Circuit Breaker
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-main-name}}?api-version={{apim-api-version}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "properties": {
    "title": "{{backend-openai-main-name}}",
    "description": "{{backend-openai-main-name}}",
    "url": "{{backend-openai-main-url}}",
    "protocol": "http",
    "tls": {
      "validateCertificateChain": true,
      "validateCertificateName": true
    },
    "circuitBreaker": {
      "rules": [
        {
          "name": "myBreakerRule",
          "tripDuration": "PT60S",
          "acceptRetryAfter": "false",
          "failureCondition": {
            "count": "1",
            "interval": "PT10S",
            "statusCodeRanges": [
              {
                "min": "429",
                "max": "429"
              }
            ]
          }
        }
      ]
    }
  }
}

###

# Backend Pool Creation or Update using PUT
PUT https://management.azure.com/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-pool-name}}?api-version={{apim-api-version}}
Authorization: Bearer {{Token}}
Content-Type: application/json

{
  "type": "Microsoft.ApiManagement/service/backends",
  "name": "{{backend-openai-pool-name}}",
  "properties": {
    "description": "{{backend-openai-pool-name}}",
    "type": "Pool",
    "pool": {
      "services": [
        {
          "id": "/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-main-name}}",
          "priority":1
        },
        {
          "id": "/subscriptions/{{subscription_id}}/resourceGroups/{{resource-group-name}}/providers/Microsoft.ApiManagement/service/{{apim-name}}/backends/{{backend-openai-fallback-name}}",
          "priority":2
        }
      ]
    }
  }
}

###