# Chat Completion - POST - the api-version value would be passed to openi, NOT to apim

# default  subscription key: de095d7c9a9d46faaf398e5d961f6aad
# standard subscription key: 
# premium  subscription key: 

@deployment-id = gpt-4o-for-apim
@openai-api-version = 2024-05-01-preview


@APIM-API-Endpoint = https://mmapim03.azure-api.net/balanced-azure-openai-service-api
@APIM-API-Operation-Path = /deployments/{{deployment-id}}/chat/completions?api-version={{openai-api-version}}
@APIM-Subscription-Key = de095d7c9a9d46faaf398e5d961f6aad


POST {{APIM-API-Endpoint}}{{APIM-API-Operation-Path}}
api-key: {{APIM-Subscription-Key}}
Content-Type: application/json

{
    "messages": [
      {
        "role": "user",
        "content": "What is a meaning function? Provide an answer with less than 20 words."
      }
    ],
    "temperature": 0,
    "top_p": 1.0,    
    "max_tokens": 1000
}