# Chat Completion - POST - the api-version value would be passed to openi, NOT to apim
@deployment-id = gpt-4o-2024-05-13
@APIM-API-Endpoint = https://mmapim01.azure-api.net/balanced-azure-open-aiservice-api
@APIM-API-Operation-Path = /openai/deployments/{{deployment-id}}/chat/completions
@APIM-Subscription-Key = 05eaa4db36254d16acfef11ac413f335


POST {{APIM-API-Endpoint}}{{APIM-API-Operation-Path}}
api-key: {{APIM-Subscription-Key}}
Content-Type: application/json

{
  "max_tokens": 500,
  "messages": [
    {
      "role": "user",
      "content": "Hi there!"
    }
  ]
}